#!/usr/bin/env bash
# transfer file from client to server

path_to_file=$1
remote_ip=$2
username=$3
path_to_ssh_key=$4
destination_folder="~/"

if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$path_to_ssh_key" "$path_to_file" "$username@$remote_ip:$destination_folder"
fi

