#!/usr/bin/env bash
# Install and configure HAProxy

haproxy_config="\
global
  daemon

defaults
  mode http

frontend my_frontend
  bind *:80
  default_backend my_backend

backend my_backend
  balance roundrobin
  server web-01 54.208.169.128
  server web-02 34.203.201.69
"

# Update the system and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Write the HAProxy configuration
sudo bash -c "echo \"$haproxy_config\" > /etc/haproxy/haproxy.cfg"

# Start HAProxy
sudo systemctl start haproxy
sudo systemctl enable haproxy

echo "HAProxy installation and configuration complete."
