#!/usr/bin/env bash
# display a list of currently running processes
# must show all processes, for all users, including those which might not have a TTY
# display in a user-oriented format
# show process hierarchy
ps -auxf
