#!/usr/bin/env bash
# print fizzbuzz logic for numbers 1..20
for i in {1..20}; do
    if ((i % 15 == 0)); then echo "FizzBuzz"
    elif ((i % 3 == 0)); then echo "Fizz"
    elif ((i % 5 == 0)); then echo "Buzz"
    else echo "$i";
    fi
done
