#!/usr/bin/env bash
# print `bad luck` for the 4th iteration
# print `good luck` for the 8th iteration
# otherwise print `Best School`
i=1
while ((i <= 10)); do
    if ((i == 4)); then echo "bad luck"
    elif ((i == 8)); then echo "good luck"
    else echo "Best School"; fi
    i=$((i + 1))
done
