#!/usr/bin/env bash
# display the content of the current directory
# in a list format where only the part of the name
# after the first dash is displayed
for file in *; do
   echo "$file" | cut -d - -f 2
done
